# Pinhole camera model with radial and tangential distortion
# (fx,fy) = focal length, (cx,cy) = principle point, (width,height) = image shape
# radial = radial distortion, (t1,t2) = tangential distortion

pinhole:
  fx: 663.0617435517213
  fy: 662.1371083791158
  cx: 303.2496801708221
  cy: 231.69684254456072
  width: 640
  height: 480
  skew: 0.0
model: pinhole_radial_tangential
radial_tangential:
  radial:
  - -0.0059470593242872015
  - -0.059020989927873926
  t1: 0.0
  t2: 0.0
version: 0
